# Generated by Django 4.2.5 on 2024-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamproject",
            name="format_prompt",
            field=models.TextField(
                blank=True,
                default="Generate an engaging summary on the topic with appropriate headings, subheadings, paragraphs, and bullet points.",
                verbose_name="Format instructions",
            ),
        ),
        migrations.AlterField(
            model_name="teamproject",
            name="summary_prompt",
            field=models.TextField(blank=True, default="", verbose_name="Summarization instructions"),
        ),
    ]
