# Generated by Django 4.2.5 on 2024-05-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_teamproject_summary_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamproject",
            name="summary_prompt",
        ),
        migrations.AddField(
            model_name="teamproject",
            name="summary_persona",
            field=models.TextField(blank=True, default="", verbose_name="Research Persona"),
        ),
    ]
