# Generated by Django 4.2.13 on 2024-07-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_remove_team_format_prompt_remove_team_summary_prompt"),
        ("projects", "0007_alter_teamproject_format_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamproject",
            name="access_teams",
            field=models.ManyToManyField(blank=True, related_name="project_access", to="teams.team"),
        ),
    ]
