# Generated by Django 4.2.13 on 2024-07-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_teamproject_access_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamproject",
            name="projects",
            field=models.ManyToManyField(blank=True, related_name="+", to="projects.teamproject"),
        ),
    ]
