#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DJANGO_SETTINGS_MODULE=config.settings.production.api

if [ -z "${REDIS_PASSWORD}" ]; then
    export REDIS_BASE_URL="redis://${REDIS_HOST}:${REDIS_PORT}"
else
    export REDIS_BASE_URL="redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}"
fi

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python << END
import sys
import time

import psycopg

suggest_unrecoverable_after = 30
start = time.time()

sys.stdout.write("Connecting to PostgreSQL database...\n")
sys.stdout.write("PostgreSQL host: {}\n".format("${POSTGRES_HOST}"))
sys.stdout.write("PostgreSQL port: {}\n".format("${POSTGRES_PORT}"))
sys.stdout.write("PostgreSQL database: {}\n".format("${POSTGRES_DB}"))
sys.stdout.write("PostgreSQL user: {}\n".format("${POSTGRES_USER}"))
sys.stdout.write("PostgreSQL password: {}...\n".format("${POSTGRES_PASSWORD}"[:4]))

while True:
    try:
        psycopg.connect(
            dbname="${POSTGRES_DB}",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

exec "$@"
