volumes:
  nexical_core_postgres_data: {}
  nexical_core_postgres_data_backups: {}
  nexical_core_redis_data: {}

services:
  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: nexical_core_node
    container_name: nexical_core_node
    depends_on:
      - ui
    volumes:
      - .:/app:z
    command: npm run dev
    ports:
      - '3000:3000'
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'

  ui: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: nexical_core_ui
    container_name: nexical_core_ui
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.env/.django
      - ./.env/.postgres
      - ./.env/.secret
    ports:
      - '8000:8000'
    command: /start-ui

  api:
    <<: *django
    image: nexical_core_api
    container_name: nexical_core_api
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8000'
    command: /start-api

  worker:
    <<: *django
    image: nexical_core_worker
    container_name: nexical_core_worker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-worker

  scheduler:
    <<: *django
    image: nexical_core_scheduler
    container_name: nexical_core_scheduler
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-scheduler

  flower:
    <<: *django
    image: nexical_core_flower
    container_name: nexical_core_flower
    ports:
      - '5555:5555'
    command: /start-flower

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: nexical_core_postgres
    container_name: nexical_core_postgres
    volumes:
      - nexical_core_postgres_data:/var/lib/postgresql/data
      - nexical_core_postgres_data_backups:/backups
      - ./restore:/restore
    env_file:
      - ./.env/.postgres
      - ./.env/.secret
    ports:
      - '5432:5432'

  redis:
    image: redis:6
    container_name: nexical_core_redis
    ports:
      - '6379:6379'
    volumes:
      - nexical_core_redis_data:/data
