# Generated by Django 4.2.5 on 2024-05-20 07:10

import app.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_alter_teamproject_format_prompt_and_more"),
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectResearchBase",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                ("id", models.CharField(max_length=65, primary_key=True, serialize=False, unique=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_data",
                        to="projects.teamproject",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="research_data", to="teams.teamtag")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectNote",
            fields=[
                (
                    "projectresearchbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="research.projectresearchbase",
                    ),
                ),
                ("message", models.TextField(verbose_name="Note Message")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
            bases=("research.projectresearchbase",),
        ),
        migrations.CreateModel(
            name="ProjectSummary",
            fields=[
                (
                    "projectresearchbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="research.projectresearchbase",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="Summary Prompt")),
                ("persona", models.TextField(blank=True, default="", verbose_name="Summary Persona")),
                ("format", models.TextField(blank=True, default="", verbose_name="Summary Format")),
                (
                    "endings",
                    app.utils.fields.ListField(blank=True, default=list, verbose_name="Summary allowed endings"),
                ),
                ("temperature", models.FloatField(default=0.1, verbose_name="Summary Temperature")),
                ("top_p", models.FloatField(default=0.9, verbose_name="Summary Top-P")),
                ("repetition_penalty", models.FloatField(default=0.9, verbose_name="Summary Repetition Penalty")),
                ("summary", models.TextField(blank=True, null=True, verbose_name="Summary")),
                ("token_count", models.IntegerField(blank=True, null=True, verbose_name="Summary Token Count")),
                ("processing_time", models.FloatField(blank=True, null=True, verbose_name="Summary Processing Time")),
                ("processing_cost", models.FloatField(blank=True, null=True, verbose_name="Summary Processing Cost")),
                ("processed_time", models.DateTimeField(blank=True, null=True, verbose_name="Processed Time")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
            bases=("research.projectresearchbase",),
        ),
        migrations.CreateModel(
            name="SummaryDocument",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("score", models.FloatField(verbose_name="Document Score")),
                ("type", models.CharField(max_length=255, verbose_name="Document Type")),
                ("document_id", models.CharField(max_length=65, verbose_name="Document ID")),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="research.projectsummary",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
