# Generated by Django 4.2.5 on 2024-05-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0003_projectsummary_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectresearchbase",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Name"),
        ),
    ]
