# Generated by Django 4.2.13 on 2024-06-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0004_projectresearchbase_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsummary",
            name="max_sections",
            field=models.IntegerField(default=10, verbose_name="Summary maximum section to parse"),
        ),
    ]
