# Generated by Django 4.2.13 on 2024-06-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0005_projectsummary_max_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsummary",
            name="sentence_limit",
            field=models.IntegerField(default=50, verbose_name="Summary Maximum Ranked Sentences per Topic"),
        ),
        migrations.AlterField(
            model_name="projectsummary",
            name="max_sections",
            field=models.IntegerField(default=10, verbose_name="Summary Maximum Sections per Topic"),
        ),
    ]
