# Generated by Django 4.2.13 on 2024-07-11 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("research", "0007_alter_projectsummary_max_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectresearchbase",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="research_artifacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
