# Generated by Django 4.2.13 on 2024-07-11 07:14

import app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0008_projectresearchbase_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsummary",
            name="use_default_format",
            field=models.BooleanField(default=True, verbose_name="Summary Use Default Format"),
        ),
        migrations.AlterField(
            model_name="projectsummary",
            name="endings",
            field=app.utils.fields.ListField(blank=True, default=list, verbose_name="Summary Allowed Endings"),
        ),
    ]
