# Generated by Django 4.2.5 on 2024-05-24 07:59

import app.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="code",
            field=models.CharField(blank=True, default="", editable=False, verbose_name="Invite Code"),
        ),
        migrations.AlterField(
            model_name="userinvite",
            name="code",
            field=models.CharField(
                blank=True,
                editable=False,
                default=app.users.models.generate_random_code,
                max_length=6,
                verbose_name="Invite Code",
            ),
        ),
    ]
