# Generated by Django 4.2.5 on 2024-05-29 02:51

import app.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userinvite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvite",
            name="code",
            field=models.CharField(
                blank=True, default=app.users.models.generate_random_code, editable=False, verbose_name="Invite Code"
            ),
        ),
    ]
