# Generated by Django 4.2.5 on 2024-05-21 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="format_prompt",
        ),
        migrations.RemoveField(
            model_name="team",
            name="summary_prompt",
        ),
    ]
