#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DJANGO_SETTINGS_MODULE=config.settings.production.base

python /app/manage.py migrate
python /app/manage.py init_roles
python /app/manage.py init_schedule

exec celery -A config.celery_app beat -l INFO
