# Generated by Django 4.2.13 on 2024-06-02 04:02

import app.outreach.models
import app.utils.fields
from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Campaign Name")),
                (
                    "csv_file",
                    private_storage.fields.PrivateFileField(
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to=app.outreach.models.campaign_file_path,
                    ),
                ),
                ("subject_template", models.CharField(max_length=512, verbose_name="Subject Template")),
                ("body_template", models.TextField(verbose_name="Body Template")),
                ("about_us", models.TextField(verbose_name="About Us")),
                ("organization_prompt", models.TextField(verbose_name="Organization Summary Prompt")),
                ("contact_prompt", models.TextField(verbose_name="Contact Summary Prompt")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("introduction", "Introductory Message"),
                            ("followup", "Follow Up Message"),
                            ("pause", "Final Message"),
                        ],
                        max_length=100,
                        verbose_name="Message Type",
                    ),
                ),
                ("organization_name", models.CharField(max_length=512, verbose_name="Organization Name")),
                ("organization_link", models.CharField(max_length=512, verbose_name="Organization URL")),
                ("organization_summary", models.TextField(blank=True, null=True, verbose_name="Organization Summary")),
                ("contact_first_name", models.CharField(max_length=256, verbose_name="Contact First Name")),
                ("contact_last_name", models.CharField(max_length=256, verbose_name="Contact Last Name")),
                ("contact_email", models.EmailField(max_length=512, verbose_name="Contact Email")),
                ("contact_city", models.CharField(blank=True, max_length=256, null=True, verbose_name="Contact City")),
                (
                    "contact_province",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="Contact Province"),
                ),
                (
                    "contact_country",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="Contact Country"),
                ),
                (
                    "contact_headline",
                    models.CharField(blank=True, max_length=512, null=True, verbose_name="Contact Headline"),
                ),
                ("contact_title", models.CharField(max_length=512, verbose_name="Contact Title")),
                (
                    "contact_seniority",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="Contact Seniority"),
                ),
                (
                    "contact_linkedin",
                    models.URLField(blank=True, max_length=512, null=True, verbose_name="Contact LinkedIn"),
                ),
                ("contact_positions", app.utils.fields.ListField(default=list, verbose_name="Contact Positions")),
                ("subject", models.CharField(max_length=512, verbose_name="Email Subject")),
                ("body", models.TextField(blank=True, null=True, verbose_name="Email Body")),
                ("sent", models.BooleanField(default=False, verbose_name="Message Sent")),
                ("failed", models.BooleanField(default=False, verbose_name="Message Failed")),
                ("skipped", models.BooleanField(default=False, verbose_name="Message Skipped")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageEvent",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("type", models.CharField(max_length=100, verbose_name="Event Type")),
                ("email", models.CharField(max_length=512, verbose_name="Email")),
                ("payload", app.utils.fields.DictionaryField(default=dict, verbose_name="Event Payload")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
