# Generated by Django 4.2.13 on 2024-06-02 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="about_us",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="body_template",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="contact_prompt",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="subject_template",
        ),
        migrations.CreateModel(
            name="CampaignEmail",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("subject_template", models.CharField(max_length=512, verbose_name="Subject template")),
                ("body_template", models.TextField(verbose_name="Body template")),
                ("wait_days", models.IntegerField(default=1, verbose_name="Wait in days before sending")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emails", to="outreach.campaign"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
