# Generated by Django 4.2.13 on 2024-06-02 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0002_remove_campaign_about_us_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignemail",
            name="wait_days",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)],
                verbose_name="Wait in days before sending (0 - 90)",
            ),
        ),
    ]
