# Generated by Django 4.2.13 on 2024-06-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0003_alter_campaignemail_wait_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="contact_positions",
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_city_column",
            field=models.CharField(default="", max_length=256, verbose_name="Contact City Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_country_column",
            field=models.CharField(default="", max_length=256, verbose_name="Contact Country Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_email_column",
            field=models.CharField(default="", max_length=256, verbose_name="Contact Email Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_first_name_column",
            field=models.CharField(default="", max_length=256, verbose_name="Contact First Name Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_headline_column",
            field=models.CharField(default="", max_length=256, verbose_name="Contact Headline Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_last_name_column",
            field=models.CharField(default="", max_length=256, verbose_name="Contact Last Name Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_linkedin_column",
            field=models.CharField(default="", max_length=256, verbose_name="Contact LinkedIn Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_province_column",
            field=models.CharField(default="", max_length=256, verbose_name="Contact Province Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_seniority_column",
            field=models.CharField(default="", max_length=256, verbose_name="Contact Seniority Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_title_column",
            field=models.CharField(default="", max_length=256, verbose_name="Contact Title Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_link_column",
            field=models.CharField(default="", max_length=256, verbose_name="Organization URL Column"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_name_column",
            field=models.CharField(default="", max_length=256, verbose_name="Organization Name Column"),
            preserve_default=False,
        ),
    ]
