# Generated by Django 4.2.13 on 2024-06-02 13:50

import app.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0004_remove_message_contact_positions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("link", models.URLField(max_length=1024, unique=True, verbose_name="Organization URL")),
                ("name", models.CharField(max_length=512, verbose_name="Organization Name")),
                (
                    "linkedin",
                    models.URLField(blank=True, max_length=1024, null=True, verbose_name="Organization LinkedIn"),
                ),
                ("description", models.CharField(max_length=512, verbose_name="Organization Description")),
                ("technologies", app.utils.fields.ListField(default=list, verbose_name="Organization Technologies")),
                ("employees", models.IntegerField(blank=True, null=True, verbose_name="Organization Employees")),
                (
                    "industry",
                    models.CharField(blank=True, max_length=512, null=True, verbose_name="Organization Industry"),
                ),
                ("keywords", app.utils.fields.ListField(default=list, verbose_name="Organization Keywords")),
                ("revenue", models.FloatField(blank=True, null=True, verbose_name="Organization Revenue")),
                ("total_funding", models.FloatField(blank=True, null=True, verbose_name="Organization Total Funding")),
                (
                    "last_funding_stage",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Organization Latest Funding Stage"
                    ),
                ),
                (
                    "last_funding",
                    models.FloatField(blank=True, null=True, verbose_name="Organization Latest Funding Amount"),
                ),
                (
                    "last_raised_at",
                    models.DateField(blank=True, null=True, verbose_name="Organization Last Raised At"),
                ),
                ("summary", models.TextField(blank=True, null=True, verbose_name="Organization Summary")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="contact_headline_column",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact_city",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact_country",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact_first_name",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact_headline",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact_last_name",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact_linkedin",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact_province",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact_seniority",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact_title",
        ),
        migrations.RemoveField(
            model_name="message",
            name="organization_link",
        ),
        migrations.RemoveField(
            model_name="message",
            name="organization_name",
        ),
        migrations.RemoveField(
            model_name="message",
            name="organization_summary",
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_departments_column",
            field=models.CharField(default="Departments", max_length=256, verbose_name="Contact Departments Column"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="contact_phone_column",
            field=models.CharField(default="First Phone", max_length=256, verbose_name="Contact Phone Column"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_description_column",
            field=models.CharField(
                default="SEO Description", max_length=256, verbose_name="Organization Description Column"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_employees_column",
            field=models.CharField(
                default="# Employees", max_length=256, verbose_name="Organization Employees Column"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_industry_column",
            field=models.CharField(default="Industry", max_length=256, verbose_name="Organization Industry Column"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_keywords_column",
            field=models.CharField(default="Keywords", max_length=256, verbose_name="Organization Keywords Column"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_last_funding_column",
            field=models.CharField(
                default="Latest Funding Amount",
                max_length=256,
                verbose_name="Organization Latest Funding Amount Column",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_last_funding_stage_column",
            field=models.CharField(
                default="Latest Funding", max_length=256, verbose_name="Organization Latest Funding Stage Column"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_last_raised_at_column",
            field=models.CharField(
                default="Last Raised At", max_length=256, verbose_name="Organization Last Raised At Column"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_linkedin_column",
            field=models.CharField(
                default="Company Linkedin Url", max_length=256, verbose_name="Organization LinkedIn Column"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_revenue_column",
            field=models.CharField(
                default="Annual Revenue", max_length=256, verbose_name="Organization Revenue Column"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_technologies_column",
            field=models.CharField(
                default="Technologies", max_length=256, verbose_name="Organization Technologies Column"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="organization_total_funding_column",
            field=models.CharField(
                default="Total Funding", max_length=256, verbose_name="Organization Total Funding Column"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="contact_city_column",
            field=models.CharField(default="City", max_length=256, verbose_name="Contact City Column"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="contact_country_column",
            field=models.CharField(default="Country", max_length=256, verbose_name="Contact Country Column"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="contact_email_column",
            field=models.CharField(default="Email", max_length=256, verbose_name="Contact Email Column"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="contact_first_name_column",
            field=models.CharField(default="First Name", max_length=256, verbose_name="Contact First Name Column"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="contact_last_name_column",
            field=models.CharField(default="Last Name", max_length=256, verbose_name="Contact Last Name Column"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="contact_linkedin_column",
            field=models.CharField(
                default="Person Linkedin Url", max_length=256, verbose_name="Contact LinkedIn Column"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="contact_province_column",
            field=models.CharField(default="State", max_length=256, verbose_name="Contact Province Column"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="contact_seniority_column",
            field=models.CharField(default="Seniority", max_length=256, verbose_name="Contact Seniority Column"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="contact_title_column",
            field=models.CharField(default="Title", max_length=256, verbose_name="Contact Title Column"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="organization_link_column",
            field=models.CharField(default="Website", max_length=256, verbose_name="Organization URL Column"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="organization_name_column",
            field=models.CharField(
                default="Company Name for Emails", max_length=256, verbose_name="Organization Name Column"
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=512, unique=True, verbose_name="Contact Email")),
                ("phone", models.CharField(max_length=256, verbose_name="Contact Phone")),
                ("first_name", models.CharField(max_length=256, verbose_name="Contact First Name")),
                ("last_name", models.CharField(max_length=256, verbose_name="Contact Last Name")),
                ("seniority", models.CharField(max_length=256, verbose_name="Contact Seniority")),
                ("title", models.CharField(max_length=512, verbose_name="Contact Title")),
                ("departments", models.CharField(verbose_name="Contact Departments")),
                ("city", models.CharField(max_length=256, verbose_name="Contact City")),
                ("province", models.CharField(max_length=256, verbose_name="Contact Province")),
                ("country", models.CharField(max_length=256, verbose_name="Contact Country")),
                ("linkedin", models.URLField(max_length=1024, verbose_name="Contact LinkedIn")),
                ("blocked", models.BooleanField(default=False, verbose_name="Contact Blocked")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="outreach.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="message",
            name="contact",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="outreach.contact"
            ),
            preserve_default=False,
        ),
    ]
