# Generated by Django 4.2.13 on 2024-06-02 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0005_organization_remove_campaign_contact_headline_column_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="organization_prompt",
        ),
    ]
