# Generated by Django 4.2.13 on 2024-06-02 16:24

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0006_remove_campaign_organization_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="contacts",
            field=app.utils.fields.ListField(default=list, verbose_name="Contact IDs"),
        ),
    ]
