# Generated by Django 4.2.13 on 2024-06-04 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0008_contactgroup_remove_campaign_contact_city_column_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="summary",
        ),
    ]
