# Generated by Django 4.2.13 on 2024-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0010_campaign_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="description",
            field=models.TextField(default="", verbose_name="Campaign Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactgroup",
            name="description",
            field=models.TextField(default="", verbose_name="Contact Group Description"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactgroup",
            name="name",
            field=models.CharField(max_length=512, verbose_name="Contact Group Name"),
        ),
    ]
