# Generated by Django 4.2.13 on 2024-06-04 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("outreach", "0011_campaign_description_contactgroup_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="description",
            field=models.TextField(default="", verbose_name="Campaign Description"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contactgroup",
            name="description",
            field=models.TextField(default="", verbose_name="Contact Group Description"),
        ),
    ]
