# Generated by Django 4.2.13 on 2024-06-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0012_alter_campaign_description_alter_campaign_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="contact_groups",
            field=models.ManyToManyField(related_name="campaigns", to="outreach.contactgroup"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Campaign Description"),
        ),
        migrations.AlterField(
            model_name="contactgroup",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Contact Group Description"),
        ),
    ]
