# Generated by Django 4.2.13 on 2024-06-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0013_campaign_contact_groups_alter_campaign_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="last_contact_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last Contact Time"),
        ),
    ]
