# Generated by Django 4.2.13 on 2024-06-04 15:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0014_contact_last_contact_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignContact",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("next_email", models.IntegerField(default=1, verbose_name="Next Email Index")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_config",
                        to="outreach.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_config",
                        to="outreach.contact",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "contact")},
            },
        ),
    ]
