# Generated by Django 4.2.13 on 2024-06-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0015_campaigncontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaigncontact",
            name="next_email",
            field=models.IntegerField(default=0, verbose_name="Next Email Index"),
        ),
    ]
