# Generated by Django 4.2.13 on 2024-06-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0016_alter_campaigncontact_next_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaigncontact",
            old_name="next_email",
            new_name="next_email_index",
        ),
        migrations.AddField(
            model_name="campaigncontact",
            name="last_contact_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last Contact Time"),
        ),
    ]
