# Generated by Django 4.2.13 on 2024-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0017_rename_next_email_campaigncontact_next_email_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(blank=True, max_length=512, verbose_name="Email Subject"),
        ),
    ]
