# Generated by Django 4.2.13 on 2024-06-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0018_alter_message_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="Email Subject"),
        ),
    ]
