# Generated by Django 4.2.13 on 2024-06-04 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0020_remove_message_type_message_campaign_message_sender"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignSequence",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("next_email_index", models.IntegerField(default=0, verbose_name="Next Email Index")),
                ("last_contact_time", models.DateTimeField(blank=True, null=True, verbose_name="Last Contact Time")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sequence", to="outreach.campaign"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sequence", to="outreach.contact"
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "contact")},
            },
        ),
        migrations.RemoveField(
            model_name="message",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="message",
            name="contact",
        ),
        migrations.DeleteModel(
            name="CampaignContact",
        ),
        migrations.AddField(
            model_name="message",
            name="sequence",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="outreach.campaignsequence",
            ),
            preserve_default=False,
        ),
    ]
