# Generated by Django 4.2.13 on 2024-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0021_campaignsequence_remove_message_campaign_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaignsequence",
            old_name="next_email_index",
            new_name="email_index",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="last_contact_time",
        ),
        migrations.AddField(
            model_name="contact",
            name="checkout_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Sales Checkout Time"),
        ),
    ]
