# Generated by Django 4.2.13 on 2024-06-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0022_rename_next_email_index_campaignsequence_email_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="email_index",
            field=models.IntegerField(default=0, verbose_name="Email Index"),
        ),
        migrations.AlterField(
            model_name="campaignsequence",
            name="email_index",
            field=models.IntegerField(default=0, verbose_name="Email Index"),
        ),
    ]
