# Generated by Django 4.2.13 on 2024-06-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0024_remove_contact_checkout_time_contactcheckout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactcheckout",
            name="contact",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="checkout", to="outreach.contact"
            ),
        ),
    ]
