# Generated by Django 4.2.13 on 2024-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0025_alter_contactcheckout_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactcheckout",
            name="time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Contact Checkout Time"),
        ),
    ]
