# Generated by Django 4.2.13 on 2024-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0027_remove_contact_contact_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="Message Processed"),
        ),
    ]
