# Generated by Django 4.2.13 on 2024-06-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0028_message_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="engaged",
            field=models.BooleanField(default=False, verbose_name="Contact Engaged"),
        ),
    ]
