# Generated by Django 4.2.13 on 2024-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0030_message_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(max_length=512, verbose_name="Contact City"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(max_length=512, verbose_name="Contact Country"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=1024, unique=True, verbose_name="Contact Email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(max_length=512, verbose_name="Contact First Name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(max_length=512, verbose_name="Contact Last Name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="province",
            field=models.CharField(max_length=512, verbose_name="Contact Province"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="seniority",
            field=models.CharField(max_length=512, verbose_name="Contact Seniority"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="title",
            field=models.CharField(max_length=1024, verbose_name="Contact Title"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.CharField(max_length=1024, verbose_name="Organization Description"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="industry",
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="Organization Industry"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="last_funding_stage",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Organization Latest Funding Stage"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=1024, verbose_name="Organization Name"),
        ),
    ]
