# Generated by Django 4.2.5 on 2024-05-18 08:00

import app.utils.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("type", models.CharField(max_length=100, verbose_name="Event Type")),
                ("data", app.utils.fields.DictionaryField(default=dict, verbose_name="Event Data")),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
