# Generated by Django 4.2.5 on 2024-05-19 22:01

import app.documents.models
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamDocumentCollection",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Document Collection Name")),
                ("processed_time", models.DateTimeField(blank=True, null=True, verbose_name="Processed Time")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_collections",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamDocument",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        storage=private_storage.storage.files.PrivateFileSystemStorage(),
                        upload_to=app.documents.models.team_document_path,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="documents.teamdocumentcollection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
