# Generated by Django 4.2.13 on 2024-06-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamdocument",
            name="description",
            field=models.TextField(blank=True, verbose_name="Document Description"),
        ),
        migrations.AddField(
            model_name="teamdocumentcollection",
            name="description",
            field=models.TextField(blank=True, verbose_name="Document Collection Description"),
        ),
    ]
