# Generated by Django 4.2.13 on 2024-07-07 06:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_alter_teamdocument_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamBookmark",
            fields=[
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="This information can help guide the AI assistants and is always available to the AI when conducting research.  The purpose of this description is to provide context on the content of this webpage.",
                        verbose_name="Webpage Description",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="documents.teamdocumentcollection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
