# Generated by Django 4.2.13 on 2024-07-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_remove_team_format_prompt_remove_team_summary_prompt"),
        ("documents", "0004_teambookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamdocumentcollection",
            name="access_teams",
            field=models.ManyToManyField(blank=True, related_name="document_collection_access", to="teams.team"),
        ),
    ]
