# Generated by Django 4.2.13 on 2024-07-07 20:54

import app.documents.models
from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_teamdocumentcollection_access_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teambookmark",
            name="url",
            field=models.URLField(max_length=500, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="teamdocument",
            name="file",
            field=private_storage.fields.PrivateFileField(
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to=app.documents.models.team_document_path,
                verbose_name="File",
            ),
        ),
    ]
