# Generated by Django 4.2.13 on 2024-07-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_remove_team_format_prompt_remove_team_summary_prompt"),
        ("documents", "0006_alter_teambookmark_url_alter_teamdocument_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamdocumentcollection",
            name="access_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="You can share this document collection with other teams on this platform. You can search teams by team name or team owner email address.",
                related_name="document_collection_access",
                to="teams.team",
            ),
        ),
    ]
